---
version: "3.5"

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    depends_on:
      - backend
      - frontend
    env_file:
      - .env
    networks:
      - internal
    ports:
      - 80:80
    volumes:
      - ./.static/:/static/
      - ./.sockets/:/sockets/

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - ./.static/:/static/

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    container_name: backend
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - internal
    tty: true
    volumes:
      - ./.static/:/static/
      - ./.sockets/:/sockets/

  db:
    container_name: db
    env_file:
      - .env
    image: postgres:10-alpine
    networks:
      - internal
    volumes:
      - .pgdata/:/var/lib/postgresql/data/

networks:
  internal:
