---
version: "3"

services:
  nginx:
    build: nginx
    container_name: nginx
    depends_on:
      - backend
      - frontend
    env_file:
      - env/dev.env
    networks:
      - internal
    ports:
      - 80:80
    volumes:
      - ./nginx:/code/

  frontend:
    build: frontend
    container_name: frontend
    env_file:
      - env/dev.env
    networks:
      - internal
    volumes:
      - ./frontend:/code/

  backend:
    build: backend
    container_name: backend
    depends_on:
      - db
    env_file:
      - env/dev.env
    networks:
      - internal
    tty: true
    volumes:
      - ./backend:/code/

  db:
    container_name: db
    env_file:
      - env/dev.env
    image: postgres:10-alpine
    networks:
      - internal
    volumes:
      - .pgdata:/var/lib/postgresql/data

networks:
  internal:
